// This file is intentionally empty.
// The gRPC service stubs that would normally live here (generated by protoc-gen-go-grpc)
// have been merged into kv.pb.go to keep the proto package self-contained
// without requiring the protoc compiler toolchain.
package proto
